"""
Human-in-the-Loop Review Manager.

Provides a SQLite-backed queue for email drafts that failed guardrail checks.
Human reviewers can approve, reject, or edit-then-approve pending drafts via
the /api/v1/review API endpoints.
"""

import json
import sqlite3
import uuid
from dataclasses import asdict, dataclass
from datetime import datetime, timezone
from enum import Enum
from typing import Any, Dict, List, Optional


class ReviewStatus(str, Enum):
    PENDING = "pending"
    APPROVED = "approved"
    REJECTED = "rejected"
    EDITED_AND_APPROVED = "edited_and_approved"


@dataclass
class ReviewRecord:
    review_id: str
    status: ReviewStatus
    created_at: str
    updated_at: str
    email_data: Dict[str, Any]        # Original email that triggered the review
    original_draft: str               # Draft generated by the LLM
    final_draft: Optional[str]        # After edit (if reviewer edited it)
    violations: List[str]             # Guardrail violations that triggered review
    risk_level: str                   # low/medium/high/critical
    reject_reason: Optional[str]      # Filled when status == rejected


class ReviewManager:
    """
    Manages the human review queue backed by the existing SQLite database.

    Usage:
        mgr = ReviewManager(db_path="./email_assistant.db")
        review_id = mgr.create_review(email_data, draft, violations, "high")
        mgr.approve(review_id)
    """

    _TABLE_SQL = """
    CREATE TABLE IF NOT EXISTS hitl_reviews (
        review_id      TEXT PRIMARY KEY,
        status         TEXT NOT NULL DEFAULT 'pending',
        created_at     TEXT NOT NULL,
        updated_at     TEXT NOT NULL,
        email_data     TEXT NOT NULL,   -- JSON
        original_draft TEXT NOT NULL,
        final_draft    TEXT,
        violations     TEXT NOT NULL,   -- JSON list
        risk_level     TEXT NOT NULL,
        reject_reason  TEXT
    )
    """

    def __init__(self, db_path: str = "./email_assistant.db"):
        self.db_path = db_path
        self._ensure_table()

    # ------------------------------------------------------------------
    # Internal helpers
    # ------------------------------------------------------------------

    def _connect(self) -> sqlite3.Connection:
        conn = sqlite3.connect(self.db_path)
        conn.row_factory = sqlite3.Row
        return conn

    def _ensure_table(self) -> None:
        with self._connect() as conn:
            conn.execute(self._TABLE_SQL)
            conn.commit()

    @staticmethod
    def _row_to_record(row: sqlite3.Row) -> ReviewRecord:
        return ReviewRecord(
            review_id=row["review_id"],
            status=ReviewStatus(row["status"]),
            created_at=row["created_at"],
            updated_at=row["updated_at"],
            email_data=json.loads(row["email_data"]),
            original_draft=row["original_draft"],
            final_draft=row["final_draft"],
            violations=json.loads(row["violations"]),
            risk_level=row["risk_level"],
            reject_reason=row["reject_reason"],
        )

    # ------------------------------------------------------------------
    # Public API
    # ------------------------------------------------------------------

    def create_review(
        self,
        email_data: Dict[str, Any],
        draft: str,
        violations: List[str],
        risk_level: str,
    ) -> str:
        """
        Create a new pending review record.

        Returns:
            review_id (str) — unique ID for this review.
        """
        review_id = str(uuid.uuid4())
        now = datetime.now(timezone.utc).isoformat()

        with self._connect() as conn:
            conn.execute(
                """
                INSERT INTO hitl_reviews
                    (review_id, status, created_at, updated_at,
                     email_data, original_draft, final_draft,
                     violations, risk_level, reject_reason)
                VALUES (?, ?, ?, ?, ?, ?, NULL, ?, ?, NULL)
                """,
                (
                    review_id,
                    ReviewStatus.PENDING.value,
                    now,
                    now,
                    json.dumps(email_data),
                    draft,
                    json.dumps(violations),
                    risk_level,
                ),
            )
            conn.commit()

        return review_id

    def get_review(self, review_id: str) -> Optional[ReviewRecord]:
        """Retrieve a single review record by ID."""
        with self._connect() as conn:
            row = conn.execute(
                "SELECT * FROM hitl_reviews WHERE review_id = ?", (review_id,)
            ).fetchone()
        return self._row_to_record(row) if row else None

    def get_pending(self) -> List[ReviewRecord]:
        """Return all reviews with status = pending, newest first."""
        with self._connect() as conn:
            rows = conn.execute(
                "SELECT * FROM hitl_reviews WHERE status = ? ORDER BY created_at DESC",
                (ReviewStatus.PENDING.value,),
            ).fetchall()
        return [self._row_to_record(r) for r in rows]

    def get_all(self, limit: int = 100) -> List[ReviewRecord]:
        """Return all reviews (any status), newest first."""
        with self._connect() as conn:
            rows = conn.execute(
                "SELECT * FROM hitl_reviews ORDER BY created_at DESC LIMIT ?",
                (limit,),
            ).fetchall()
        return [self._row_to_record(r) for r in rows]

    def approve(self, review_id: str) -> ReviewRecord:
        """
        Approve a pending review — the original draft will be used as-is.

        Raises:
            ValueError: if review does not exist or is not pending.
        """
        return self._transition(review_id, ReviewStatus.APPROVED)

    def reject(self, review_id: str, reason: str = "") -> ReviewRecord:
        """
        Reject a pending review, discarding the draft.

        Args:
            review_id: ID of the review to reject.
            reason: Optional human-readable reason for rejection.
        """
        record = self._get_pending_or_raise(review_id)
        now = datetime.now(timezone.utc).isoformat()
        with self._connect() as conn:
            conn.execute(
                """
                UPDATE hitl_reviews
                SET status = ?, updated_at = ?, reject_reason = ?
                WHERE review_id = ?
                """,
                (ReviewStatus.REJECTED.value, now, reason, review_id),
            )
            conn.commit()
        return self.get_review(review_id)

    def edit_and_approve(self, review_id: str, edited_draft: str) -> ReviewRecord:
        """
        Replace the draft with an edited version and approve.

        Args:
            review_id: ID of the review.
            edited_draft: The corrected email text.
        """
        self._get_pending_or_raise(review_id)
        now = datetime.now(timezone.utc).isoformat()
        with self._connect() as conn:
            conn.execute(
                """
                UPDATE hitl_reviews
                SET status = ?, updated_at = ?, final_draft = ?
                WHERE review_id = ?
                """,
                (
                    ReviewStatus.EDITED_AND_APPROVED.value,
                    now,
                    edited_draft,
                    review_id,
                ),
            )
            conn.commit()
        return self.get_review(review_id)

    # ------------------------------------------------------------------
    # Helpers
    # ------------------------------------------------------------------

    def _transition(self, review_id: str, new_status: ReviewStatus) -> ReviewRecord:
        self._get_pending_or_raise(review_id)
        now = datetime.now(timezone.utc).isoformat()
        with self._connect() as conn:
            conn.execute(
                "UPDATE hitl_reviews SET status = ?, updated_at = ? WHERE review_id = ?",
                (new_status.value, now, review_id),
            )
            conn.commit()
        return self.get_review(review_id)

    def _get_pending_or_raise(self, review_id: str) -> ReviewRecord:
        record = self.get_review(review_id)
        if record is None:
            raise ValueError(f"Review '{review_id}' not found.")
        if record.status != ReviewStatus.PENDING:
            raise ValueError(
                f"Review '{review_id}' is not pending "
                f"(current status: {record.status.value})."
            )
        return record
